version: 2.1

executors:
  maven-executor:
    docker:
      - image: codaress/openjdk-22  # Use the codaress OpenJDK 22 image
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Verify Java Version
          command: java -version
      - run:
          name: Download Dependencies
          command: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

  test:
    executor: maven-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Run Tests
          command: mvn clean test
      - store_artifacts:
          path: target/surefire-reports
      - store_test_results:
          path: target/surefire-reports

workflows:
  version: 2
  test:
    jobs:
      - build
      - test:
          requires:
            - build
